# Generated by Django 5.2.8 on 2025-11-09 14:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('job_scrape', 'Job Scraping'), ('resume_match', 'Resume Matching'), ('resume_customize', 'Resume Customization'), ('auto_apply', 'Auto Apply'), ('email_sent', 'Email Sent'), ('follow_up', 'Follow-up'), ('sync', 'Data Sync'), ('error', 'Error')], max_length=30)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['log_type', 'timestamp'], name='JobSprout_a_log_typ_9aa39e_idx'), models.Index(fields=['success', 'timestamp'], name='JobSprout_a_success_392c7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(default='Bengaluru', max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('target_roles', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('salary_expectation', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_apply_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=200)),
                ('company_website', models.URLField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(default='Full-time', max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(default=list)),
                ('experience_required', models.CharField(blank=True, max_length=50)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('source_url', models.URLField()),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('matched', 'Matched'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='new', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['company', 'title'], name='JobSprout_a_company_029339_idx'), models.Index(fields=['status', 'is_active'], name='JobSprout_a_status_95a84f_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('strength_areas', models.JSONField(default=list)),
                ('improvement_areas', models.JSONField(default=list)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('apply_priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='JobSprout_ai.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='JobSprout_ai.job')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomizedResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customized_summary', models.TextField()),
                ('customized_skills', models.JSONField(default=list)),
                ('customized_experience', models.JSONField(default=list)),
                ('keywords_added', models.JSONField(default=list)),
                ('file_path', models.FileField(upload_to='resumes/customized/')),
                ('firebase_url', models.URLField(blank=True)),
                ('ats_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ats_analysis', models.JSONField(default=dict)),
                ('generation_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_resumes', to='JobSprout_ai.jobmatch')),
            ],
            options={
                'ordering': ['-ats_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('auto_apply', 'Auto Apply'), ('email_recruiter', 'Email to Recruiter'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('viewed', 'Viewed'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('offered', 'Offer Received'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('auto_follow_up', models.BooleanField(default=True)),
                ('follow_up_count', models.IntegerField(default=0)),
                ('last_follow_up', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customized_resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobSprout_ai.customizedresume')),
                ('job_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='JobSprout_ai.jobmatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('contact_type', models.CharField(choices=[('recruiter', 'Recruiter'), ('hr', 'HR Manager'), ('hiring_manager', 'Hiring Manager'), ('team_lead', 'Team Lead'), ('cto', 'CTO'), ('founder', 'Founder')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('found_via', models.CharField(default='Hunter.io', max_length=50)),
                ('confidence_score', models.FloatField(default=0)),
                ('is_contacted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='JobSprout_ai.job')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
                'unique_together': {('job', 'email')},
            },
        ),
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('replied', 'Replied'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('gmail_message_id', models.CharField(blank=True, max_length=200)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_messages', to='JobSprout_ai.application')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobSprout_ai.outreachmessage')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='JobSprout_ai.recruitercontact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('original_file', models.FileField(upload_to='resumes/original/')),
                ('firebase_url', models.URLField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('experience_years', models.FloatField(default=0)),
                ('education', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('key_achievements', models.JSONField(default=list)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='JobSprout_ai.candidate')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('candidate', 'version')},
            },
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='JobSprout_ai.resume'),
        ),
        migrations.AddField(
            model_name='customizedresume',
            name='original_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobSprout_ai.resume'),
        ),
        migrations.AlterUniqueTogether(
            name='jobmatch',
            unique_together={('job', 'resume')},
        ),
    ]
